AUDIO_FEATURE_ENABLED_KPI_OPTIMIZE := true
BOARD_USES_ALSA_AUDIO := true
USE_CUSTOM_AUDIO_POLICY := 1

# "New Sample Rate" is the default sample rate now
AUDIO_FEATURE_ENABLED_NEW_SAMPLE_RATE := true
# AUDIO_FEATURE_ENABLED_COMPRESS_VOIP := true
# AUDIO_FEATURE_ENABLED_MULTI_VOICE_SESSIONS := true
# AUDIO_FEATURE_ENABLED_RECORD_PLAY_CONCURRENCY := true
# AUDIO_FEATURE_ENABLED_VOICE_CONCURRENCY := true